# Adds a "Sponsor" button to the top of the GitHub repo page.
# Configuration reference: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [christopherwells]
