// Daily archive: which past dailies can be replayed, and which replay
// completions are allowed to feed the par-model fit.
//
// Two independent gates live here so the client and the test suite read the
// same rules from one place:
//   1. isArchivableDate  — is this date offered in the archive at all?
//   2. archiveSubmitPlan — what does a completion do (fit row? history row?)
//
// Pure module: no DOM, no Firebase, no clock. Callers pass the dates in.
// YYYY-MM-DD strings compare correctly with < and >= because they are
// fixed-width and zero-padded, so no Date parsing is needed.

// The first ET date the archive offers — the app's launch (2026-03-06, v0.1).
// Canonical storage only began 2026-04-27; the launch..04-26 boards were
// regenerated from each date's seed with the current pipeline and written by
// scripts/backfill-old-dailies.mjs. Those are fresh no-guess dailies stamped
// with old dates, NOT recreations of the per-device boards originally played
// (unrecoverable — never stored), and they're all below ARCHIVE_FIT_EPOCH so
// they never feed the par fit. See the Daily Archive section of CLAUDE.md.
export const FIRST_ARCHIVE_DATE = '2026-03-06';

// The first ET date a canonical `dailyBoard` was written by the live pipeline,
// and therefore the first date on which the stored board and its `dailyMeta`
// describe the SAME board. Before it, the board was regenerated by the
// backfill while the meta still describes the per-device board actually
// played, so the two legitimately disagree and a recompute of one against the
// other proves nothing. That is provenance, not tampering.
//
// The R refit already draws this line as DIGIT_ERA_START (it derives the
// clue-digit shares from stored boards, so it cannot reach back past it);
// `test/verifyCanonicals.test.mjs` cross-checks that the two still agree.
export const CANONICAL_ERA_START = '2026-04-27';

// Archive completions only feed the par fit from the date per-user
// dailyHistory began recording (the dailyHistory ship, 2026-05-07). A
// completion for an earlier date could double-count against a live play that
// pre-dates history and so left no dailyHistory row to dedupe against, so an
// earlier date never submits a fit row (it stays playable, just out of the
// fit). See PR 3 / Daily Archive in CLAUDE.md.
export const ARCHIVE_FIT_EPOCH = '2026-05-07';

// localStorage key prefix marking that the player previewed a date's crux via
// PR 4's `?crux=` route. The archive submit reads `<prefix><date>` and tags
// the row `cruxViewed: true` so the refit drops it (a previewed crux changes
// the completion time). PR 4 owns the writer; defined here so reader and
// writer share one key. Nothing sets it until PR 4 ships, so it reads false.
export const CRUX_VIEWED_KEY_PREFIX = 'minesweeper_crux_viewed_';

/**
 * Is `date` offered in the archive? True for a stored past date: at or after
 * the first canonical, and strictly before today (today is the live Daily's
 * job, never the archive's). Canonical existence is probed separately at
 * launch; this gate is the cheap date-window check the calendar uses.
 *
 * @param {string} date  YYYY-MM-DD (ET) of the candidate board
 * @param {string} today YYYY-MM-DD (ET) of the current day
 * @param {string} [firstDate] override for the first archivable date
 * @returns {boolean}
 */
export function isArchivableDate(date, today, firstDate = FIRST_ARCHIVE_DATE) {
  if (typeof date !== 'string' || typeof today !== 'string') return false;
  return date >= firstDate && date < today;
}

/**
 * What the archive calendar should do with one day cell.
 *
 *   'playable'    — offered, tap to play
 *   'done'        — offered but already finished, so it shows its completion
 *                   mark and is NOT tappable. A daily is a one-off: once you
 *                   have finished a board there is nothing left to find on it,
 *                   and re-running it records nothing anyway (archiveSubmitPlan
 *                   is first-completion-only). The calendar keeps showing it so
 *                   the month reads as a completion map (Christopher, 2026-07-18).
 *   'today'       — the live Daily's job, never the archive's
 *   'unavailable' — outside the archive window
 *
 * `completed` may be a Set, an array, or null. NULL MEANS UNKNOWN, not empty:
 * a signed-out player or a failed history read cannot be told which boards they
 * have finished, and blocking the whole calendar on a flaky read would be worse
 * than letting a replay through. Fail OPEN here deliberately — the data is
 * protected either way, because archiveSubmitPlan already fails CLOSED on an
 * unknown history and records nothing.
 *
 * @param {string} date  YYYY-MM-DD (ET) of the cell
 * @param {string} today YYYY-MM-DD (ET)
 * @param {Set<string>|string[]|null} [completed] board dates already finished
 * @param {string} [firstDate] override for the first archivable date
 * @returns {'playable'|'done'|'today'|'unavailable'}
 */
export function archiveDayState(date, today, completed = null, firstDate = FIRST_ARCHIVE_DATE) {
  if (typeof date !== 'string' || typeof today !== 'string') return 'unavailable';
  if (date === today) return 'today';
  if (!isArchivableDate(date, today, firstDate)) return 'unavailable';
  if (!completed) return 'playable';
  const has = completed instanceof Set ? completed.has(date) : completed.includes(date);
  return has ? 'done' : 'playable';
}

/**
 * Decide what an archive completion for `date` does, given whether the player
 * already has a dailyHistory row for it.
 *
 *   submitFit    — push a dailyArchive/{date} row for the par fit. Gated on
 *                  the epoch so pre-history dates can never double-count.
 *   writeHistory — write users/{uid}/dailyHistory/{date}. This is both the
 *                  first-completion dedup key (a present row means "already
 *                  played, this is a replay") and the source the delta chart
 *                  reads, so an archived board slots into the chart with no
 *                  migration.
 *
 * A replay (history already present) does neither: first completion wins.
 *
 * Only a CONFIRMED-absent row is a first completion. 'unknown' means the
 * dailyHistory read failed or Firebase wasn't ready, and we must FAIL CLOSED:
 * a replay mis-read as fresh would double-feed the par fit (push-keyed
 * dailyArchive rows don't overwrite) and overwrite the first-completion chart
 * row. Record nothing and let a later healthy completion pick it up.
 * (REGRESSION: archive dedup fail-open — a failed/early read returned null and
 * was treated as "no prior completion", so a flaky read on a replay double-fed
 * the fit.)
 *
 * @param {string} date YYYY-MM-DD (ET) of the played board
 * @param {'present'|'absent'|'unknown'} historyStatus does
 *   users/{uid}/dailyHistory/{date} exist? 'present' = replay, 'absent' = first
 *   completion, 'unknown' = read failed / Firebase not ready.
 * @param {string} [epoch] override for the fit epoch
 * @returns {{ submitFit: boolean, writeHistory: boolean }}
 */
export function archiveSubmitPlan(date, historyStatus, epoch = ARCHIVE_FIT_EPOCH) {
  if (historyStatus !== 'absent') return { submitFit: false, writeHistory: false };
  return {
    submitFit: typeof date === 'string' && date >= epoch,
    writeHistory: true,
  };
}

/**
 * Resolve the `?crux=` share-route date with a spoiler + range guard. The route
 * shows a PAST daily's crux, so today and later are REFUSED (never spoil the
 * live board) and anything before the first canonical is out of range; both
 * fall back to yesterday. An empty / non-date param ('' or '1') also defaults
 * to yesterday. Pure string compares (fixed-width YYYY-MM-DD).
 *
 * @param {string} cruxParam   the raw ?crux= value ('', '1', or YYYY-MM-DD)
 * @param {string} todayET     today's ET date
 * @param {string} yesterdayET yesterday's ET date (the default + clamp target)
 * @param {string} [firstDate] earliest offered date
 * @returns {string} YYYY-MM-DD to show
 */
export function resolveCruxDate(cruxParam, todayET, yesterdayET, firstDate = FIRST_ARCHIVE_DATE) {
  let cruxDate = /^\d{4}-\d{2}-\d{2}$/.test(cruxParam) ? cruxParam : yesterdayET;
  if (cruxDate >= todayET || cruxDate < firstDate) cruxDate = yesterdayET;
  return cruxDate;
}

/**
 * Filter a loadDailyHistory() result down to the dates the streak may derive
 * from. Archive replays write dailyHistory rows too (the calendar's completed
 * marks and the delta chart need them), but they carry `archive: true` and
 * must be invisible to the streak reconciler — otherwise replaying a past gap
 * day retroactively splices the run together and inflates the streak and the
 * monotonic bestDailyStreak (issue #113).
 *
 * @param {Array<{date: string, archive?: boolean}>|null} entries
 * @returns {string[]} the live-completion 'YYYY-MM-DD' dates
 */
export function streakBearingDates(entries) {
  if (!Array.isArray(entries)) return [];
  return entries
    .filter((e) => e && typeof e.date === 'string' && e.archive !== true)
    .map((e) => e.date);
}

/**
 * The play-timeline attribution rule for a dailyHistory row. dailyHistory is
 * keyed by the BOARD's date (the dedup key and the calendar mark), but the
 * time-series surfaces (history chart, career-vs-rolling averages) must place
 * a play on the day it was actually PLAYED:
 *  - a LIVE row belongs to its board date — the run happened on that ET day
 *    even when the write itself flushed from the retry queue days later;
 *  - an ARCHIVE replay belongs to the ET day of its submittedAt — plotting it
 *    at the board's date back-dates today's performance into the past and
 *    corrupts the rolling/career averages.
 *
 * @param {string} dateKey       the row's YYYY-MM-DD board-date key
 * @param {boolean} isArchive    the row's archive marker
 * @param {number}  submittedAtMs the row's submittedAt (server ms)
 * @param {(ms: number) => string|null} etOfMs timestamp → ET date string
 * @returns {string} the YYYY-MM-DD day the play belongs to on a timeline
 */
export function attributePlayedDate(dateKey, isArchive, submittedAtMs, etOfMs) {
  if (isArchive !== true) return dateKey;
  return etOfMs(submittedAtMs) || dateKey;
}
